// <auto-generated />
namespace CRM.BusinessLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CRMModelShopDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CRMModelShopDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202001101808568_CRM Model Shop DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
